sonar.projectKey=ajmaquilon97_app-client-react-native
sonar.organization=ajmaquilon97

sonar.projectName=app-client-react-native
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/__tests__/**,**/node_modules/**,**/coverage/**,**/android/**,**/.expo/**

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
